apiVersion: v1
kind: Service
metadata:
  name: {{ include "voicevox.fullname" . }}
  labels:
    {{- include "voicevox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50021
      protocol: TCP
      name: http
  selector:
    {{- include "voicevox.selectorLabels" . | nindent 4 }}
